RaiblocksApiService:
    Db:
        LogsConnString:
            settings-key: "RaiblocksApiService-LogsConnString"
            types:
                - AzureBlobStorage
                - Tag

        DataConnString:
            settings-key: "RaiblocksApiService-DataConnString"
            types:
                - AzureTableStorage      
                - Tag
    NodeAPI:
        NodeURL:
            settings-key: "RaiblocksApiService-NodeURL"
            types:
                - Tag
            
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl       

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName: "slack-notifications"